spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jwm_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  pattern:
    dateformat: HH:mm:ss
mybatis:
  mapper-locations: classpath*:mapper/*.xml





# springdoc-openapi项目配置 接口文档配置
#访问地址：localhost:8080/doc.html
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.vaughan.javawebmaster.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  # 开启增强配置
  enable: true
  # 开启Swagger的Basic认证功能,默认是false
#basic:
#  enable: true
#  # Basic认证用户名
#  #认证似乎有点问题，本地无法开启，建议线上也不要开启
#  username: Vaughan
#  # Basic认证密码
#  password: 654321